#!/usr/bin/env sh

echo "------ HOOK START - BUILD -------"
printenv

docker build \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg BUILD_NAME="$IMAGE_NAME" \
  --build-arg BUILD_VERSION="$DOCKER_TAG" \
  --build-arg BUILD_COMMIT="$GIT_SHA1" \
  -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
